Kudu.Web/Models/Application.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Kudu.Web.Models
{
    public class Application : IApplication
    {
        public Application()
        {
            SiteUrls = new List<string>();
        }

        public string Name { get; set; }
        public string ServiceUrl
        {
            get
            {
                return ServiceUrls[0];
            }
        }
        public string SiteUrl
        {
            get
            {
                return SiteUrls[0];
            }
        }
        public IList<string> SiteUrls { get; set; }
        public IList<string> ServiceUrls { get; set; }
    }
}

Kudu.Web/Models/ApplicationViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web.Mvc;
using Kudu.Core.Deployment;
using Kudu.Core.SourceControl;
using Kudu.SiteManagement;
using Kudu.SiteManagement.Certificates;
using Kudu.SiteManagement.Configuration;
using Kudu.SiteManagement.Context;

namespace Kudu.Web.Models
{
    public class ApplicationViewModel
    {
        public ApplicationViewModel()
        {
            Schemas = new[]
            {
                new SelectListItem {Text = "Http://", Value = "Http://", Selected = true},
                new SelectListItem {Text = "Https://", Value = "Https://"}
            };
        }

        public ApplicationViewModel(IApplication application, IKuduContext context,
            IEnumerable<Certificate> certificates)
            : this()
        {
            //Certificates = certificates;
            Name = application.Name;
            SiteUrl = application.SiteUrl;
            SiteUrls = application.SiteUrls;
            ServiceUrl = application.ServiceUrl;
            ServiceUrls = application.ServiceUrls;

            CustomHostNames = context.Configuration.CustomHostNamesEnabled;

            Certificates = certificates
                .Select(cert => new SelectListItem { Text = cert.FriendlyName, Value = cert.Thumbprint })
                .ToArray();

            IpAddresses = (new[] { new SelectListItem {Text = "All Unassigned", Value = "*", Selected = true } })
                .Union(context.IPAddresses.Select(ip => new SelectListItem { Text = ip, Value = ip }))
                .ToArray();

            SupportsSni = context.IISVersion.Major == 8;
        }

        [Required]
        public string Name { get; set; }
        public string SiteUrl { get; set; }
        public IEnumerable<string> SiteUrls { get; set; }
        public string ServiceUrl { get; set; }
        public IEnumerable<string> ServiceUrls { get; set; }
        public bool CustomHostNames { get; private set; }
        public RepositoryInfo RepositoryInfo { get; set; }
        public bool SupportsSni { get; set; }

        public string GitUrl
        {
            get
            {
                if (RepositoryInfo == null)
                {
                    return null;
                }
                return RepositoryInfo.GitUrl.ToString();
            }
        }

        public IList<DeployResult> Deployments { get; set; }

        public string CloneUrl
        {
            get
            {
                if (RepositoryInfo == null)
                {
                    return null;
                }

                switch (RepositoryInfo.Type)
                {
                    case RepositoryType.Git:
                        return GitUrl;
                }
                return null;
            }
        }

        public IEnumerable<SelectListItem> Schemas { get; set; }
        public IEnumerable<SelectListItem> Certificates { get; set; }
        public IEnumerable<SelectListItem> IpAddresses { get; set; }
    }
}

Kudu.Web/Controllers/ApplicationController.cs
using System;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using Kudu.Client.Infrastructure;
using Kudu.SiteManagement;
using Kudu.SiteManagement.Certificates;
using Kudu.SiteManagement.Configuration;
using Kudu.SiteManagement.Configuration.Section;
using Kudu.SiteManagement.Context;
using Kudu.Web.Infrastructure;
using Kudu.Web.Models;

namespace Kudu.Web.Controllers
{
    public class ApplicationController : Controller
    {
        private readonly IApplicationService _applicationService;
        private readonly KuduEnvironment _environment;
        private readonly IKuduContext _context;
        private readonly ICertificateSearcher _certificates;
        private readonly ICredentialProvider _credentialProvider;

        public ApplicationController(IApplicationService applicationService,
                                     ICredentialProvider credentialProvider,
                                     KuduEnvironment environment,
                                     IKuduContext context, 
                                     ICertificateSearcher certificates)
        {
            _applicationService = applicationService;
            _credentialProvider = credentialProvider;
            _environment = environment;
            _context = context;
            _certificates = certificates;
        }

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            ViewBag.showAdmingWarning = !_environment.IsAdmin && _environment.RunningAgainstLocalKuduService;
            base.OnActionExecuting(filterContext);
        }

        public ViewResult Index()
        {
            var applications = (from name in _applicationService.GetApplications()
                                orderby name
                                select name).ToList();

            return View(applications);
        }

        public Task<ActionResult> Details(string slug)
        {
            return GetApplicationView("settings", "Details", slug);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(string name)
        {
            string slug = name.GenerateSlug();

            try
            {
                await _applicationService.AddApplication(slug);

                return RedirectToAction("Details", new { slug });
            }
            catch (SiteExistsException)
            {
                ModelState.AddModelError("Name", "Site already exists");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }

            return View("Create");
        }

        [HttpPost]
        public async Task<ActionResult> Delete(string slug)
        {
            if (await _applicationService.DeleteApplication(slug))
            {
                return RedirectToAction("Index");
            }

            return HttpNotFound();
        }

        [HttpPost]
        [ActionName("add-custom-site-binding")]
        public async Task<ActionResult> AddCustomSiteBinding(string slug, string siteSchema, string siteIp, string sitePort, string siteHost, string siteRequireSni, string siteCertificate)
        {
            IApplication application = _applicationService.GetApplication(slug);

            if (application == null)
            {
                return HttpNotFound();
            }

            _applicationService.AddSiteBinding(slug, new KuduBinding {
                Schema = siteSchema.Equals("https://", StringComparison.OrdinalIgnoreCase) ? UriScheme.Https : UriScheme.Http,
                Ip = siteIp,
                Port = int.Parse(sitePort),
                Host = siteHost,
                Sni = bool.Parse(siteRequireSni),
                Certificate = siteCertificate,
                SiteType = SiteType.Live
            });

            return await GetApplicationView("settings", "Details", slug);
        }

        [HttpPost]
        [ActionName("remove-custom-site-binding")]
        public async Task<ActionResult> RemoveCustomSiteBinding(string slug, string siteBinding)
        {
            IApplication application = _applicationService.GetApplication(slug);

            if (application == null)
            {
                return HttpNotFound();
            }

            _applicationService.RemoveLiveSiteBinding(slug, siteBinding);

            return await GetApplicationView("settings", "Details", slug);
        }

        [HttpPost]
        [ActionName("add-service-site-binding")]
        public async Task<ActionResult> AddServiceSiteBinding(string slug, string siteSchema, string siteIp, string sitePort, string siteHost, string siteRequireSni, string siteCertificate)
        {
            IApplication application = _applicationService.GetApplication(slug);

            if (application == null)
            {
                return HttpNotFound();
            }

            _applicationService.AddSiteBinding(slug, new KuduBinding {
                Schema = siteSchema.Equals("https://", StringComparison.OrdinalIgnoreCase) ? UriScheme.Https : UriScheme.Http,
                Ip = siteIp,
                Port = int.Parse(sitePort),
                Host = siteHost,
                Sni = bool.Parse(siteRequireSni),
                Certificate = siteCertificate,
                SiteType = SiteType.Service
            });

            return await GetApplicationView("settings", "Details", slug);
        }

        [HttpPost]
        [ActionName("remove-service-site-binding")]
        public async Task<ActionResult> RemoveServiceSiteBinding(string slug, string siteBinding)
        {
            IApplication application = _applicationService.GetApplication(slug);

            if (application == null)
            {
                return HttpNotFound();
            }

            _applicationService.RemoveServiceSiteBinding(slug, siteBinding);

            return await GetApplicationView("settings", "Details", slug);
        }

        private async Task<ActionResult> GetApplicationView(string tab, string viewName, string slug)
        {
            var application = _applicationService.GetApplication(slug);

            ICredentials credentials = _credentialProvider.GetCredentials();
            var repositoryInfo = await application.GetRepositoryInfo(credentials);
            var appViewModel = new ApplicationViewModel(application, _context, _certificates.FindAll());
            appViewModel.RepositoryInfo = repositoryInfo;

            ViewBag.slug = slug;
            ViewBag.tab = tab;
            ViewBag.appName = appViewModel.Name;
            ViewBag.siteBinding = String.Empty;

            ModelState.Clear();

            return View(viewName, appViewModel);
        }
    }
}

Kudu.Web/Views/Application/Create.cshtml
@model Kudu.Web.Models.ApplicationViewModel

@{
    ViewBag.Title = "New Application";
}

@if (!ViewData.ModelState.IsValid)
{ 
<div class="alert alert-error">
@Html.ValidationSummary(true)
</div>
}

@using (Html.BeginForm())
{    
  <fieldset>
    <legend>New Application</legend>
    <div class="control-group">
      @Html.LabelFor(model => model.Name)
      <div class="controls">        
        @Html.EditorFor(model => model.Name)
        @Html.ValidationMessageFor(model => model.Name)
        <p class="help-block">Name of the application</p>
      </div>
    </div>
    <p>
        <input type="submit" value="Create application" class="btn-primary" />
    </p>
  </fieldset>
}

Kudu.Web/Views/Application/Details.cshtml
@using System.Activities.Expressions
@using Kudu.Core.SourceControl
@using Kudu.Web.Models
@using Kudu.Web.Infrastructure

@model ApplicationViewModel
@{
    ViewBag.Title = Model.Name;
}

<form class="well form-inline">
    <label class="control-label"><strong>GIT URL</strong></label>
    <input type="input" id="clone-url" name="name" value="@Model.GitUrl" readonly="readonly" />
</form>

<div class="well">
    <div class="control-group">
        <label class="control-label"><strong>Application URL</strong></label>
        <div class="controls">
            <a href="@Model.SiteUrl" target="_blank">@Model.SiteUrl</a>
            <p class="help-block">This is the link to your website.</p>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label"><strong>Service URL</strong></label>
        <div class="controls">
            <a href="@Model.ServiceUrl" target="_blank">@Model.ServiceUrl</a>
            <p class="help-block">This is the link to the kudu service.</p>
        </div>
    </div>
</div>

<script type="text/javascript">
    //Note: Would be so nice with a proper frontend framework like, EmberJS, AngularJS or React!
    function removeBinding(binding, element) {
        if (confirm('Remove the following site binding: ' + binding)) {
            $(element).val(binding).closest('form').submit();
        }
    }

    var BindingForm = (function () {
        //Note: Util
        function getFormField(form, field) {
            return $('#' + form + field);
        }

        function isDef(val) {
            return typeof val !== 'undefined';
        }

        function propertyFn(formField) {
            return function(value) {
                if (isDef(value)) {
                    getFormField(this.name, formField).val(value);
                    return this;
                }
                return getFormField(this.name, formField).val();
            }
        }

        function BindingForm(name) {
            this.name = name;
        }

        //[0].checked

        BindingForm.prototype.schema = propertyFn('SiteSchema');
        BindingForm.prototype.port = propertyFn('SitePort');
        BindingForm.prototype.hostName = propertyFn('SiteHost');

        BindingForm.prototype.sniEnabled = function(value) {
            if (isDef(value)) {
                getFormField(this.name, 'SniEnabled')[0].checked = value;
                return this;
            }
            return getFormField(this.name, 'SniEnabled')[0].checked;
        }

        BindingForm.prototype.certificate = function (value) {
            if (isDef(value)) {
                getFormField(this.name, 'SiteCertificate').val(null);
            }
            return getFormField(this.name, 'SiteCertificate').children('option:selected').text();
        }

        BindingForm.prototype.httpsFields = function () {
            var selector = '.' + this.name + 'HttpsFields';
            return $(selector);
        }

        BindingForm.prototype.hostNameField = function() {
            return getFormField(this.name, 'SiteHost');
        }

        return BindingForm;
    })();

    function getForm(form) {
        return new BindingForm(form);
    }

    function schemaChanged(form) {
        form = getForm(form);
        if (form.schema() == 'Https://') {
            form.httpsFields().show();
            form.port(443);
        } else {
            form.httpsFields().hide();
            form.port(80);
        }
    }

    function httpsChanged(form) {
        form = getForm(form);
        //Note: We know the form is HTTPS here.

        var cert = form.certificate();
        if (cert[0] === '*' || (supportsSni() && form.sniEnabled())) {
            form.hostNameField().prop('disabled', false);
        } else {
            form.hostName("");
            form.hostNameField().prop('disabled', true);
        }
    }

    function supportsSni() {
        return @Model.SupportsSni.ToString().ToLower();
    }
</script>

@helper AddBindingForm(string name, string action, string controller)
{
    //Note: Lets mimic the entire IIS dialog instead so it is more familiar to IIS administrators.
    using (Html.BeginForm(action, controller, new { slug = Model.Name.GenerateSlug() }, FormMethod.Post))
    {
        <label class="control-label"><strong>Add binding</strong></label>           
        @Html.ValidationSummary()

        <div class="row">
            <div class="span2">
                <label class="control-label">Type:</label>
                @Html.DropDownList("siteSchema", Model.Schemas, new { onchange = "schemaChanged('" + name + "')", id = name + "SiteSchema", style = "width: 100%;" })
            </div>
            <div class="span4">
                <label class="control-label">IP address:</label>
                @Html.DropDownList("siteIp", Model.IpAddresses, new { style = "width: 100%", id = name + "SiteIp" })
            </div>
            <div class="span2">
                <label class="control-label">Port:</label>
                @Html.TextBox("sitePort", "80", new { style = "width: 50%", id = name + "SitePort" })
            </div>
        </div>
        <div class="row">
            <div class="span5">
                <label>Host name:</label>
                @Html.TextBox("siteHost", "", new { placeholder = "example.org", style = "width: 100%", id = name + "SiteHost" })
            </div>
        </div>
        if (Model.SupportsSni)
        {
            <div style="display: none;" class="row @(name + "HttpsFields")">
                <div class="span5">
                    <label class="checkbox">
                        @Html.CheckBox("siteRequireSni", false, new { id = name + "SniEnabled", onchange = "httpsChanged('" + name + "')" }) Require Server Name Indication
                    </label>
                </div>
            </div>
        }
        <div style="display: none; margin-top: 20px;" class="row @(name + "HttpsFields")">
            <div class="span5">
                <label>SSL certificate:</label>
                @Html.DropDownList("siteCertificate", Model.Certificates, "Select certificate...", new { onchange = "httpsChanged('" + name + "')", style = "width: 100%", id = name + "SiteCertificate" })
            </div>
        </div>
        <button id="add_sitebinding" type="submit" class="btn btn-primary">Add binding</button>
    }
}

@if (Model.CustomHostNames)
{
    <div class="well">
        <div class="control-group">
            <label class="control-label"><strong>Custom Application Site Bindings</strong></label>
            <p class="help-block">
            Specify additional site bindings for the service site.  Can be of the format 'hostname', 'hostname:port', 'example.org' or 'example.org:port'.
        </p>
            <p class="help-block">
                Protocol is limited to http only and all bindings entered will be set to http.
            </p>

            @if (Model.SiteUrls.Any())
            {

                <table id="custom-site-bindings" class="table">
                    <tr>
                        <th>Protocol</th>
                        <th>Hostname</th>
                        <th>Port</th>
                        <th></th>
                    </tr>
                    @foreach (string siteBinding in Model.SiteUrls.Skip(1))
                    {
                        var uri = new Uri(siteBinding);
                        
                        <tr>
                            <td>@uri.Scheme</td>
                            <td><a href="@uri.AbsoluteUri">@uri.Host</a></td>
                            <td>@uri.Port</td>
                            <td class="actions">
                                <button type="button" class="btn btn-primary" onclick=" removeBinding('@siteBinding', '#removesitebinding') ">Remove</button>
                            </td>
                        </tr>
                    }

                </table>
                
                    using (Html.BeginForm("remove-custom-site-binding", "Application", new { slug = Model.Name.GenerateSlug() }, FormMethod.Post, new { id = "remove-site-binding-form" }))
                    {
                    @Html.Hidden("siteBinding", "", new { id = "removesitebinding" })
                    }

            }
            
            @AddBindingForm("app", "add-custom-site-binding", "Application")

        </div>
    </div>
    
    <div class="well">
        <div class="control-group">
            <label class="control-label"><strong>Custom Service Site Bindings</strong></label>
            
            <p class="help-block">
            Specify additional site bindings for the service site.  Can be of the format 'hostname', 'hostname:port', 'example.org' or 'example.org:port'.
        </p>
            <p class="help-block">
            Protocol is limited to http only and all bindings entered will be set to http.
            </p>

            @if (Model.ServiceUrls.Any())
            {

                <table id="custom-site-bindings" class="table">
                    <tr>
                        <th>Protocol</th>
                        <th>Hostname</th>
                        <th>Port</th>
                        <th></th>
                    </tr>
                    @foreach (string siteBinding in Model.ServiceUrls.Skip(1))
                    {
                        var uri = new Uri(siteBinding);
                        
                        <tr>
                            <td>@uri.Scheme</td>
                            <td><a href="@uri.AbsoluteUri">@uri.Host</a></td>
                            <td>@uri.Port</td>
                            <td class="actions">
                                <button type="button" class="btn btn-primary" onclick=" removeBinding('@siteBinding', '#removeservicebinding') ">Remove</button>
                            </td>
                        </tr>
                    }

                </table>
                
                using (Html.BeginForm("remove-service-site-binding", "Application", new { slug = Model.Name.GenerateSlug() }, FormMethod.Post, new { id = "remove-site-binding-form" }))
                {
                    @Html.Hidden("siteBinding", "", new { id = "removeservicebinding" })
                }
            }
            
            @AddBindingForm("scm", "add-service-site-binding", "Application")

        </div>
    </div>
}

@using (Html.BeginForm("Delete", "Application", new { slug = Model.Name.GenerateSlug() }))
{ 
    <input type="submit" class="btn-danger btn-large" name="name" value="Delete Application" />
}

Kudu.Web/Views/Application/Index.cshtml
@using Kudu.Core.SourceControl
@using Kudu.Web.Models
@using Kudu.Web.Infrastructure

@model IEnumerable<string>

@{
    ViewBag.Title = "Applications";
}

<div class="well">
    <ul class="nav nav-list">
        <li class="nav-header">Applications</li>
        @foreach (var item in Model)
        {
            <li>
                @using (Html.BeginForm("Delete", "Application", new { slug = item.GenerateSlug() }))
                {
                    <div class="row-fluid">
                        <button type="submit" class="plain"><i class="icon icon-remove"></i></button>
                        <a href="@Url.RouteUrl("ApplicationDetails", new { slug = item })" class="site-item">
                            <i class="icon-th-list"></i>
                            @item
                        </a>
                    </div>
                }
            </li>
        }
    </ul>
</div>